---
# Kubernetes 버전
k8s_version: 1.34.3

# 클러스터 네트워크
k8s_pod_network_cidr: 10.244.0.0/16
k8s_service_cidr: 10.96.0.0/12
k8s_master_ip: 10.200.1.10

# CNI 플러그인
k8s_cni_plugin: flannel

# Container Runtime
containerd_version: "1.7"
